name: Checker

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  checker-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Checker And Sent Teams Notification
        run: python checker.py --url ${{ secrets.MS_TEAMS_WEBHOOK_URI }} --words ${{ secrets.WORDS_TO_TRACK_IN_TITLE }}
      - uses: gautamkrishnar/keepalive-workflow@master # https://github.com/gautamkrishnar/keepalive-workflow
